using Sentry;
using Sentry.Extensibility;
using System.Net;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using System;
using System.Linq;
using Overseer.Services.Providers;
using Overseer.Services.Tools;

namespace Overseer.Services
{
    public class AuthSentryEventProcessor : ISentryEventProcessor
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        /* The three providers' public hosts plus the external tool hosts, and now the custom
           endpoint hosts an operator allowlisted.

           Instance-resolved rather than static because configuration is not available at type
           initialisation. That change is not cosmetic: a self-hosted endpoint absent from this
           set stops having its transient failures suppressed, so a model server restarting
           reports a stream of Sentry events -- each one carrying the endpoint's URL. */
        private readonly string[] _externalServiceHosts;

        private static readonly string[] OfficialProviderHosts = GoogleProvider.ProviderHosts
            .Concat(AnthropicProvider.ProviderHosts)
            .Concat(OpenAiResponsesProvider.ProviderHosts)
            .Concat(ExternalToolHosts.AllHosts)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        /* Header names and query parameter names whose values are removed before an event
           leaves the process. Matched case-insensitively and, for query parameters, by exact
           name rather than substring -- "code" must not also blank "postcode". */
        private static readonly string[] ScrubbedHeaders =
        {
            "Authorization", "Cookie", "Set-Cookie", "Proxy-Authorization",
            "X-XSRF-TOKEN", "X-Api-Key", "X-Sentry-Auth"
        };

        private static readonly string[] ScrubbedQueryKeys =
        {
            "token", "key", "apiKey", "api_key", "password", "code", "secret", "access_token"
        };

        private const string Scrubbed = "[scrubbed]";

        /// <summary>
        /// Tag and <c>HttpContext.Items</c> key marking an event as raised inside a
        /// confidential session. The second and third of the three drop signals; the first is
        /// <see cref="Privacy.ConfidentialExecutionScope"/>.
        /// </summary>
        public const string ConfidentialTagName = "overseer.confidential";

        public AuthSentryEventProcessor(
            IHttpContextAccessor httpContextAccessor,
            Overseer.Services.Privacy.EndpointPolicy? endpointPolicy = null)
        {
            _httpContextAccessor = httpContextAccessor;

            /* Only literally allowlisted hosts join the set. A wildcard pattern has no host to
               name, and matching event URLs against a wildcard here would suppress more than
               the operator allowlisted. */
            _externalServiceHosts = endpointPolicy == null
                ? OfficialProviderHosts
                : OfficialProviderHosts
                    .Concat(endpointPolicy.AllowedLiteralHosts)
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .ToArray();
        }

        public SentryEvent? Process(SentryEvent @event)
        {
            var httpContext = _httpContextAccessor.HttpContext;

            /* Confidential sessions send nothing to Sentry. Checked first, and on three
               independent signals, because each alone has a hole: the AsyncLocal is the
               reliable one and survives a streaming turn that outlives its request; the scope
               tag depends on an SDK ordering contract; and the HttpContext item only exists
               while a request does. Any of the three drops the event. */
            if (Privacy.ConfidentialExecutionScope.IsConfidential
                || @event.Tags.ContainsKey(ConfidentialTagName)
                || httpContext?.Items.ContainsKey(ConfidentialTagName) == true)
            {
                return null;
            }

            if (httpContext != null && httpContext.User?.Identity?.IsAuthenticated != true)
            {
                // Drop events from unauthenticated web requests (bots, probes)
                return null;
            }

            bool isExternalService = IsExternalServiceTarget(@event);

            // Check if the event or its inner exceptions contain a transient HttpRequestException
            if (IsTransientApiOverloadException(@event.Exception, isExternalService))
            {
                return null;
            }

            // Check if the event was generated by SentryHttpFailedRequestHandler for transient external service responses
            if (IsTransientHttpFailedRequestEvent(@event, isExternalService))
            {
                return null;
            }

            /* Scrubbing runs last, on the events that are actually being sent. The SDK's own
               SendDefaultPii = false already suppresses much of this; doing it here as well
               means an SDK default change, or an option set somewhere else, cannot widen the
               surface without this method agreeing. */
            Scrub(@event);

            return @event;
        }

        /// <summary>
        /// Removes credentials and identity from an outgoing event: named request headers,
        /// named query values, and the whole user record.
        /// </summary>
        private static void Scrub(SentryEvent @event)
        {
            var request = @event.Request;
            if (request != null)
            {
                foreach (var name in ScrubbedHeaders)
                {
                    if (request.Headers.ContainsKey(name))
                        request.Headers[name] = Scrubbed;
                }

                /* Cookies live in their own property as well as in the Cookie header. */
                if (!string.IsNullOrEmpty(request.Cookies))
                    request.Cookies = Scrubbed;

                request.QueryString = ScrubQueryString(request.QueryString);
                request.Url = ScrubUrl(request.Url);
            }

            /* The user is identified by the authenticated session Overseer already knows
               about; a Sentry event does not need the address, the name or the IP to be
               actionable, and those are the fields that make a crash report personal data. */
            @event.User.Email = null;
            @event.User.Username = null;
            @event.User.IpAddress = null;
            @event.User.Other?.Clear();

            foreach (var tag in ScrubbedQueryKeys)
            {
                if (@event.Tags.ContainsKey(tag))
                    @event.SetTag(tag, Scrubbed);
            }
        }

        /// <summary>Blanks the value of every sensitive parameter, keeping the shape of the query.</summary>
        internal static string? ScrubQueryString(string? queryString)
        {
            if (string.IsNullOrEmpty(queryString))
                return queryString;

            bool leadingQuestionMark = queryString[0] == '?';
            string body = leadingQuestionMark ? queryString[1..] : queryString;

            var parts = body.Split('&');
            for (int i = 0; i < parts.Length; i++)
            {
                int eq = parts[i].IndexOf('=');
                if (eq <= 0)
                    continue;

                string name = parts[i][..eq];
                if (ScrubbedQueryKeys.Contains(name, StringComparer.OrdinalIgnoreCase))
                    parts[i] = name + "=" + Scrubbed;
            }

            return (leadingQuestionMark ? "?" : string.Empty) + string.Join("&", parts);
        }

        /// <summary>Applies the same scrubbing to the query part of a full URL.</summary>
        internal static string? ScrubUrl(string? url)
        {
            if (string.IsNullOrEmpty(url))
                return url;

            int q = url.IndexOf('?');
            if (q < 0)
                return url;

            return url[..q] + ScrubQueryString(url[q..]);
        }

        private bool IsExternalServiceTarget(SentryEvent @event)
        {
            string? url = @event.Request?.Url;
            if (string.IsNullOrEmpty(url) && @event.Tags.TryGetValue("url", out var tagUrl))
            {
                url = tagUrl;
            }
            if (string.IsNullOrEmpty(url) && @event.Tags.TryGetValue("Uri", out var tagUri))
            {
                url = tagUri;
            }

            if (!string.IsNullOrEmpty(url) && _externalServiceHosts.Any(host => url.Contains(host, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }

            return IsExternalServiceException(@event.Exception);
        }

        private bool IsExternalServiceException(Exception? exception)
        {
            if (exception == null)
            {
                return false;
            }

            if (exception is HttpRequestException httpEx && !string.IsNullOrEmpty(httpEx.Message))
            {
                if (_externalServiceHosts.Any(host => httpEx.Message.Contains(host, StringComparison.OrdinalIgnoreCase)))
                {
                    return true;
                }
            }

            if (exception is AggregateException aggEx)
            {
                foreach (var inner in aggEx.InnerExceptions)
                {
                    if (IsExternalServiceException(inner))
                    {
                        return true;
                    }
                }
            }
            else if (exception.InnerException != null)
            {
                return IsExternalServiceException(exception.InnerException);
            }

            return false;
        }

        private bool IsTransientApiOverloadException(Exception? exception, bool isExternalService)
        {
            if (exception == null)
            {
                return false;
            }

            if (exception is HttpRequestException httpEx)
            {
                // Globally drop standard transient overload status codes
                if (httpEx.StatusCode == HttpStatusCode.TooManyRequests || 
                    httpEx.StatusCode == HttpStatusCode.BadGateway || 
                    httpEx.StatusCode == HttpStatusCode.ServiceUnavailable ||
                    httpEx.StatusCode == HttpStatusCode.GatewayTimeout ||
                    (int?)httpEx.StatusCode == 529)
                {
                    return true;
                }

                // For external services (AI providers, GitHub, NetHackWiki), drop ALL 5xx server errors (including 500, 501)
                if (isExternalService && httpEx.StatusCode.HasValue && (int)httpEx.StatusCode.Value >= 500 && (int)httpEx.StatusCode.Value <= 599)
                {
                    return true;
                }

                if (httpEx.Message != null)
                {
                    if (httpEx.Message.Contains("503") ||
                        httpEx.Message.Contains("502") ||
                        httpEx.Message.Contains("429") ||
                        httpEx.Message.Contains("504") ||
                        httpEx.Message.Contains("529"))
                    {
                        return true;
                    }

                    if (isExternalService && (httpEx.Message.Contains("500") || httpEx.Message.Contains("501")))
                    {
                        return true;
                    }
                }

                // If exception is targeted to an external service and represents a network transport failure without status code
                if (isExternalService && !httpEx.StatusCode.HasValue)
                {
                    return true;
                }
            }

            if (exception is AggregateException aggEx)
            {
                foreach (var inner in aggEx.InnerExceptions)
                {
                    if (IsTransientApiOverloadException(inner, isExternalService))
                    {
                        return true;
                    }
                }
            }
            else if (exception.InnerException != null)
            {
                return IsTransientApiOverloadException(exception.InnerException, isExternalService);
            }

            return false;
        }

        private bool IsTransientHttpFailedRequestEvent(SentryEvent @event, bool isExternalService)
        {
            bool isHttpFailedRequestHandler = false;

            if (@event.SentryExceptions?.Any(e => string.Equals(e.Mechanism?.Type, "SentryHttpFailedRequestHandler", StringComparison.OrdinalIgnoreCase)) == true)
            {
                isHttpFailedRequestHandler = true;
            }
            else if (@event.Tags.TryGetValue("mechanism", out var mechanism) && string.Equals(mechanism, "SentryHttpFailedRequestHandler", StringComparison.OrdinalIgnoreCase))
            {
                isHttpFailedRequestHandler = true;
            }
            else if (@event.Message?.Formatted?.Contains("Response status code does not indicate success", StringComparison.OrdinalIgnoreCase) == true)
            {
                isHttpFailedRequestHandler = true;
            }

            if (!isHttpFailedRequestHandler)
            {
                return false;
            }

            // Extract HTTP status code
            int? statusCode = null;
            if (@event.Contexts.Response?.StatusCode.HasValue == true)
            {
                statusCode = (int)@event.Contexts.Response.StatusCode.Value;
            }
            else if (@event.Tags.TryGetValue("response.status_code", out var codeStr) && int.TryParse(codeStr, out var parsedCode))
            {
                statusCode = parsedCode;
            }
            else if (@event.Tags.TryGetValue("status_code", out var codeStr2) && int.TryParse(codeStr2, out var parsedCode2))
            {
                statusCode = parsedCode2;
            }
            else if (@event.Message?.Formatted != null)
            {
                var msg = @event.Message.Formatted;
                if (msg.Contains("503")) statusCode = 503;
                else if (msg.Contains("502")) statusCode = 502;
                else if (msg.Contains("429")) statusCode = 429;
                else if (msg.Contains("504")) statusCode = 504;
                else if (msg.Contains("529")) statusCode = 529;
                else if (msg.Contains("500")) statusCode = 500;
                else if (msg.Contains("501")) statusCode = 501;
            }

            // Drop transient overload status codes and all 5xx for external services (AI providers & tools)
            if (isExternalService && statusCode.HasValue)
            {
                if (statusCode == 429 || (statusCode >= 500 && statusCode <= 599))
                {
                    return true;
                }
            }

            return false;
        }
    }
}
