using Sentry;
using Sentry.Extensibility;
using System.Net;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using System;
using System.Linq;
using Overseer.Services.Providers;
using Overseer.Services.Tools;

namespace Overseer.Services
{
    public class AuthSentryEventProcessor : ISentryEventProcessor
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        private static readonly string[] ExternalServiceHosts = GoogleProvider.ProviderHosts
            .Concat(AnthropicProvider.ProviderHosts)
            .Concat(OpenAiResponsesProvider.ProviderHosts)
            .Concat(ExternalToolHosts.AllHosts)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        public AuthSentryEventProcessor(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public SentryEvent? Process(SentryEvent @event)
        {
            var httpContext = _httpContextAccessor.HttpContext;

            if (httpContext != null && httpContext.User?.Identity?.IsAuthenticated != true)
            {
                // Drop events from unauthenticated web requests (bots, probes)
                return null;
            }

            bool isExternalService = IsExternalServiceTarget(@event);

            // Check if the event or its inner exceptions contain a transient HttpRequestException
            if (IsTransientApiOverloadException(@event.Exception, isExternalService))
            {
                return null;
            }

            // Check if the event was generated by SentryHttpFailedRequestHandler for transient external service responses
            if (IsTransientHttpFailedRequestEvent(@event, isExternalService))
            {
                return null;
            }

            return @event;
        }

        private bool IsExternalServiceTarget(SentryEvent @event)
        {
            string? url = @event.Request?.Url;
            if (string.IsNullOrEmpty(url) && @event.Tags.TryGetValue("url", out var tagUrl))
            {
                url = tagUrl;
            }
            if (string.IsNullOrEmpty(url) && @event.Tags.TryGetValue("Uri", out var tagUri))
            {
                url = tagUri;
            }

            if (!string.IsNullOrEmpty(url) && ExternalServiceHosts.Any(host => url.Contains(host, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }

            return IsExternalServiceException(@event.Exception);
        }

        private bool IsExternalServiceException(Exception? exception)
        {
            if (exception == null)
            {
                return false;
            }

            if (exception is HttpRequestException httpEx && !string.IsNullOrEmpty(httpEx.Message))
            {
                if (ExternalServiceHosts.Any(host => httpEx.Message.Contains(host, StringComparison.OrdinalIgnoreCase)))
                {
                    return true;
                }
            }

            if (exception is AggregateException aggEx)
            {
                foreach (var inner in aggEx.InnerExceptions)
                {
                    if (IsExternalServiceException(inner))
                    {
                        return true;
                    }
                }
            }
            else if (exception.InnerException != null)
            {
                return IsExternalServiceException(exception.InnerException);
            }

            return false;
        }

        private bool IsTransientApiOverloadException(Exception? exception, bool isExternalService)
        {
            if (exception == null)
            {
                return false;
            }

            if (exception is HttpRequestException httpEx)
            {
                // Globally drop standard transient overload status codes
                if (httpEx.StatusCode == HttpStatusCode.TooManyRequests || 
                    httpEx.StatusCode == HttpStatusCode.BadGateway || 
                    httpEx.StatusCode == HttpStatusCode.ServiceUnavailable ||
                    httpEx.StatusCode == HttpStatusCode.GatewayTimeout ||
                    (int?)httpEx.StatusCode == 529)
                {
                    return true;
                }

                // For external services (AI providers, GitHub, NetHackWiki), drop ALL 5xx server errors (including 500, 501)
                if (isExternalService && httpEx.StatusCode.HasValue && (int)httpEx.StatusCode.Value >= 500 && (int)httpEx.StatusCode.Value <= 599)
                {
                    return true;
                }

                if (httpEx.Message != null)
                {
                    if (httpEx.Message.Contains("503") ||
                        httpEx.Message.Contains("502") ||
                        httpEx.Message.Contains("429") ||
                        httpEx.Message.Contains("504") ||
                        httpEx.Message.Contains("529"))
                    {
                        return true;
                    }

                    if (isExternalService && (httpEx.Message.Contains("500") || httpEx.Message.Contains("501")))
                    {
                        return true;
                    }
                }

                // If exception is targeted to an external service and represents a network transport failure without status code
                if (isExternalService && !httpEx.StatusCode.HasValue)
                {
                    return true;
                }
            }

            if (exception is AggregateException aggEx)
            {
                foreach (var inner in aggEx.InnerExceptions)
                {
                    if (IsTransientApiOverloadException(inner, isExternalService))
                    {
                        return true;
                    }
                }
            }
            else if (exception.InnerException != null)
            {
                return IsTransientApiOverloadException(exception.InnerException, isExternalService);
            }

            return false;
        }

        private bool IsTransientHttpFailedRequestEvent(SentryEvent @event, bool isExternalService)
        {
            bool isHttpFailedRequestHandler = false;

            if (@event.SentryExceptions?.Any(e => string.Equals(e.Mechanism?.Type, "SentryHttpFailedRequestHandler", StringComparison.OrdinalIgnoreCase)) == true)
            {
                isHttpFailedRequestHandler = true;
            }
            else if (@event.Tags.TryGetValue("mechanism", out var mechanism) && string.Equals(mechanism, "SentryHttpFailedRequestHandler", StringComparison.OrdinalIgnoreCase))
            {
                isHttpFailedRequestHandler = true;
            }
            else if (@event.Message?.Formatted?.Contains("Response status code does not indicate success", StringComparison.OrdinalIgnoreCase) == true)
            {
                isHttpFailedRequestHandler = true;
            }

            if (!isHttpFailedRequestHandler)
            {
                return false;
            }

            // Extract HTTP status code
            int? statusCode = null;
            if (@event.Contexts.Response?.StatusCode.HasValue == true)
            {
                statusCode = (int)@event.Contexts.Response.StatusCode.Value;
            }
            else if (@event.Tags.TryGetValue("response.status_code", out var codeStr) && int.TryParse(codeStr, out var parsedCode))
            {
                statusCode = parsedCode;
            }
            else if (@event.Tags.TryGetValue("status_code", out var codeStr2) && int.TryParse(codeStr2, out var parsedCode2))
            {
                statusCode = parsedCode2;
            }
            else if (@event.Message?.Formatted != null)
            {
                var msg = @event.Message.Formatted;
                if (msg.Contains("503")) statusCode = 503;
                else if (msg.Contains("502")) statusCode = 502;
                else if (msg.Contains("429")) statusCode = 429;
                else if (msg.Contains("504")) statusCode = 504;
                else if (msg.Contains("529")) statusCode = 529;
                else if (msg.Contains("500")) statusCode = 500;
                else if (msg.Contains("501")) statusCode = 501;
            }

            // Drop transient overload status codes and all 5xx for external services (AI providers & tools)
            if (isExternalService && statusCode.HasValue)
            {
                if (statusCode == 429 || (statusCode >= 500 && statusCode <= 599))
                {
                    return true;
                }
            }

            return false;
        }
    }
}
