// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileGnollHackLogger.Data;

#nullable disable

namespace GnollHackServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901112514_AddDisplayNameMode")]
    partial class AddDisplayNameMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.Bones", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BonesFilePath")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlatformVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Port")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PortBuild")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PortVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("VersionCompatibilityNumber")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VersionNumber")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.ToTable("Bones");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.BonesTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("BonesId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlatformVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Port")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PortBuild")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PortVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("VersionCompatibilityNumber")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VersionNumber")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.ToTable("BonesTransactions");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualServiceTierUsed")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ChatSessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("ModelDisplayNameUsed")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderUsed")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReasoningModeUsed")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ServiceTierUsed")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ThinkingLevelUsed")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("TimeToFirstTokenMs")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDurationMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId", "TimestampUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ChatSessionId", "TimestampUtc"), new[] { "Role", "IsHidden", "ModelUsed", "ProviderUsed", "TimeToFirstTokenMs", "TotalDurationMs" });

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatMessageAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.ToTable("ChatMessageAttachment");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatMessageToolCall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ArgsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BatchIndex")
                        .HasColumnType("int");

                    b.Property<long>("ChatMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExecutionMs")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentToolCallId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("QueueWaitMs")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ToolCallId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId", "SortOrder");

                    b.ToTable("ChatMessageToolCall");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientSettings")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGnollHackSession")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMessageUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "DeletedUtc");

                    b.HasIndex("AspNetUserId", "IsDeleted", "LastMessageUtc")
                        .IsDescending(false, false, true);

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AspNetUserId", "IsDeleted", "LastMessageUtc"), new[] { "Title", "IsGnollHackSession", "IsPinned" });

                    b.ToTable("ChatSession");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.GameLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AchievementsBinary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AchievementsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alignment")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BirthDateText")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<long?>("ByteEnd")
                        .HasColumnType("bigint");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<long?>("ByteStart")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ConductsBinary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConductsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeathDateText")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("DeathDungeonNumber")
                        .HasColumnType("int");

                    b.Property<int>("DeathLevel")
                        .HasColumnType("int");

                    b.Property<string>("DeathText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DungeonCollapses")
                        .HasColumnType("int");

                    b.Property<int>("EditLevel")
                        .HasColumnType("int");

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint");

                    b.Property<long>("EndTimeUTC")
                        .HasColumnType("bigint");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<string>("FlagsBinary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlatformVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<string>("Port")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PortBuild")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("PortSecurityLevel")
                        .HasColumnType("int");

                    b.Property<string>("PortVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProcessUserID")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("RealTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Scoring")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<long>("StartTimeUTC")
                        .HasColumnType("bigint");

                    b.Property<string>("StartingAlignment")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("StartingGender")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Store")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Tournament")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Turns")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("WhileText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.ToTable("GameLog");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.GroupSystemAiApiConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DailyChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("DailyChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("DailyTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("DailyTitleTokensCount")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDailyReset")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMonthlyReset")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxDailyChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxDailyChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxDailyTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxDailyTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxMonthlyChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxMonthlyChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxMonthlyTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxMonthlyTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxTotalChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxTotalChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxTotalTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxTotalTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("ModelRole")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("MonthlyChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("MonthlyTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("MonthlyTitleTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long>("SystemAiApiConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("TotalChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("TotalTitleTokensCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SystemAiApiConfigurationId");

                    b.ToTable("GroupSystemAiApiConfigurations");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.RequestInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<bool?>("DecryptionSucceeded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FirstDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("LastDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid?>("LastRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool?>("LoginSucceeded")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestAntiForgeryToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RequestUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("int");

                    b.Property<int?>("SubType")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserIPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SaveFileTracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileLength")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.HasIndex("TimeStamp", "AspNetUserId")
                        .IsUnique()
                        .HasFilter("[AspNetUserId] IS NOT NULL");

                    b.ToTable("SaveFileTrackings");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SystemAiApiConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKeyNonce")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ApiKeyTag")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("DailyChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("DailyTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("DailyTitleTokensCount")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayNameMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EncryptedApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsBudgetExhausted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemWide")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastBudgetNotificationSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastDailyReset")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMonthlyReset")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxDailyChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxDailyChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxDailyTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxDailyTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxInputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("MaxMonthlyChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxMonthlyChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxMonthlyTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxMonthlyTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTotalChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxTotalChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxTotalTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxTotalTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ModelRole")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("MonthlyChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("MonthlyTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("MonthlyTitleTokensCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ParallelExecutionMode")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReasoningMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReasoningSummary")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ServiceTier")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ThinkingLevel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TotalChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("TotalChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("TotalTitleTokensCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SystemAiApiConfigurations");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SystemAiErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DismissedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DismissedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<long>("SystemAiApiConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DismissedByUserId");

                    b.HasIndex("SystemAiApiConfigurationId");

                    b.ToTable("SystemAiErrorLogs");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SystemAiUsageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CacheCreationInputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("CacheReadInputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RoleContext")
                        .HasColumnType("int");

                    b.Property<long>("SystemAiApiConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalDurationMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.HasIndex("SystemAiApiConfigurationId", "TimestampUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SystemAiApiConfigurationId", "TimestampUtc"), new[] { "AspNetUserId", "RoleContext", "InputTokens", "OutputTokens" });

                    b.ToTable("SystemAiUsageLogs");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserAiApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKeyNonce")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ApiKeyTag")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EncryptedApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("ParallelExecutionMode")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId", "Provider")
                        .IsUnique();

                    b.ToTable("UserAiApiKeys");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserAiModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("MaxInputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReasoningMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReasoningSummary")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ServiceTier")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ThinkingLevel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.ToTable("UserAiModels");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserAiSettings", b =>
                {
                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EnableClientTools")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableGameActions")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableSubAgents")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableToolUse")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableWebSearch")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCallsPerSession")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParallelToolCalls")
                        .HasColumnType("int");

                    b.Property<int?>("MaxResultLength")
                        .HasColumnType("int");

                    b.Property<int?>("MaxToolIterations")
                        .HasColumnType("int");

                    b.Property<int?>("RequestTimeout")
                        .HasColumnType("int");

                    b.Property<bool>("ShowParallelBadge")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSourceCodeReferences")
                        .HasColumnType("bit");

                    b.Property<int>("ShowThoughtsAndTools")
                        .HasColumnType("int");

                    b.Property<bool>("SpoilerFreeMode")
                        .HasColumnType("bit");

                    b.Property<bool>("TitleGenerationDisabled")
                        .HasColumnType("bit");

                    b.Property<long?>("TitleGenerationModelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TitleGenerationSystemModelId")
                        .HasColumnType("bigint");

                    b.HasKey("AspNetUserId");

                    b.ToTable("UserAiSettings");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserGroup", b =>
                {
                    b.Property<string>("AspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.HasKey("AspNetUserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserSystemAiApiConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DailyChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("DailyChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("DailyTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("DailyTitleTokensCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDailyReset")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMonthlyReset")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxDailyChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxDailyChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxDailyTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxDailyTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxMonthlyChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxMonthlyChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxMonthlyTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxMonthlyTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxTotalChatRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxTotalChatTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxTotalTitleRequests")
                        .HasColumnType("int");

                    b.Property<long?>("MaxTotalTitleTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("ModelRole")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("MonthlyChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("MonthlyTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("MonthlyTitleTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long>("SystemAiApiConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalChatRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("TotalChatTokensCount")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTitleRequestsCount")
                        .HasColumnType("int");

                    b.Property<long>("TotalTitleTokensCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.HasIndex("SystemAiApiConfigurationId");

                    b.ToTable("UserSystemAiApiConfigurations");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool?>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBonesBanned")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGameLogBanned")
                        .HasColumnType("bit");

                    b.Property<string>("JunetHackUserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.Bones", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.BonesTransaction", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatMessage", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatMessageAttachment", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatMessageToolCall", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ChatMessage", "ChatMessage")
                        .WithMany("ToolCalls")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatSession", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.GameLog", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany("GameLogs")
                        .HasForeignKey("AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.GroupSystemAiApiConfiguration", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.Group", "Group")
                        .WithMany("GroupSystemAiApiConfigurations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileGnollHackLogger.Data.SystemAiApiConfiguration", "SystemAiApiConfiguration")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("SystemAiApiConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("SystemAiApiConfiguration");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.RequestInfo", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SaveFileTracking", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SystemAiErrorLog", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "DismissedByUser")
                        .WithMany()
                        .HasForeignKey("DismissedByUserId");

                    b.HasOne("MobileGnollHackLogger.Data.SystemAiApiConfiguration", "SystemAiApiConfiguration")
                        .WithMany("ErrorLogs")
                        .HasForeignKey("SystemAiApiConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DismissedByUser");

                    b.Navigation("SystemAiApiConfiguration");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SystemAiUsageLog", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany("SystemAiUsageLogs")
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileGnollHackLogger.Data.SystemAiApiConfiguration", "SystemAiApiConfiguration")
                        .WithMany("UsageLogs")
                        .HasForeignKey("SystemAiApiConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");

                    b.Navigation("SystemAiApiConfiguration");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserAiApiKey", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserAiModel", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserAiSettings", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserGroup", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany("UserGroups")
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileGnollHackLogger.Data.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.UserSystemAiApiConfiguration", b =>
                {
                    b.HasOne("MobileGnollHackLogger.Data.ApplicationUser", "AspNetUser")
                        .WithMany("UserSystemAiApiConfigurations")
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileGnollHackLogger.Data.SystemAiApiConfiguration", "SystemAiApiConfiguration")
                        .WithMany("UserAssignments")
                        .HasForeignKey("SystemAiApiConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");

                    b.Navigation("SystemAiApiConfiguration");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ChatMessage", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.Group", b =>
                {
                    b.Navigation("GroupSystemAiApiConfigurations");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.SystemAiApiConfiguration", b =>
                {
                    b.Navigation("ErrorLogs");

                    b.Navigation("GroupAssignments");

                    b.Navigation("UsageLogs");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("MobileGnollHackLogger.Data.ApplicationUser", b =>
                {
                    b.Navigation("GameLogs");

                    b.Navigation("SystemAiUsageLogs");

                    b.Navigation("UserGroups");

                    b.Navigation("UserSystemAiApiConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
